# spring
spring:
  jackson:
    default-property-inclusion: non_null
  redis:
      host: ${address.redis}
      port: 6379
#      password: 123456
      timeout: 0
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

druid:
  url: jdbc:mysql://${address.mysql}:3306/appdb
  username: root
  password: 123456
  driverClassName: com.mysql.jdbc.Driver
  type: com.alibaba.druid.pool.DruidDataSource
  # 下面为连接池的补充设置，应用到上面所有数据源中
  # 初始化大小，最小，最大
  initialSize: 5
  minIdle: 5
  maxActive: 20
  # 配置获取连接等待超时的时间
  maxWait: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1 FROM DUAL
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  # 打开PSCache，并且指定每个连接上PSCache的大小
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  filters: stat,log4j2
  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  # 合并多个DruidDataSource的监控数据
  #useGlobalDataSourceStat: true

# Mybatis
mybatis:
#  mapperLocations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml

management:
  endpoints:
    web:
      base-path: /actuator
#      exposure:
#        include: ['health']
  server:
    port: 8081

server:
  servlet:
    context-path: /api
  port: 8080

#通用mapper
#mappers 多个接口时逗号隔开
mapper:
  mappers: com.raven.appserver.common.BaseMapper
  not-empty: true
  before: true
  identity: mysql

rest:
  timeout: 15000

app:
  url: http://${address.im}:8060/raven/admin/
  key: xxxxx
  secret: xxxxx

address:
  mysql: 127.0.0.1
  redis: 127.0.0.1
  im: 127.0.0.1

fdfs:
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - xxxxx:22122
  pool:
      max-total: 150         #从池中借出的对象的最大数目
      max-wait-millis: 100   #获取连接时的最大等待毫秒数100

  res-host: xxxxx
  storage-port: 8888

qiniu:
  appKey: xxxxx
  secret: xxxxx
  bucket: xxxxx

